FROM library/ubuntu:16.04
RUN apt-get update
RUN apt-get -y upgrade python
RUN apt-get -y upgrade python-pip
RUN apt-get -y upgrade git
RUN apt-get -y upgrade libpq-dev
RUN apt-get -y install postgresql-client
RUN mkdir /opt/subrosa
RUN git clone https://github.com/ayohrling/subrosa.git /opt/subrosa
RUN ls /opt/subrosa
ADD startup_docker.sh /opt/subrosa
ADD subrosa.conf /opt/subrosa
WORKDIR /opt/subrosa
RUN ./install --postgres
